### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Beavermon** [chunkaligned/fabric-discord-integration#17]
what is the rconUserIDs and how do I use it? do you have discord that we can chat on to figure this out? thaanks!

**Comment by hkva** [comment]
`rconUserIDs` is a list of Discord users that can use the `mc!rcon` command, which allows them to run admin commands on the Minecraft server from Discord.

```json
{
  "token": "omitted",
  "commandPrefix": "mc!",
  "relayChannelIDs": [ 1049063127075004476 ],
  "rconUserIDs": [ 678461241332596737, 1109876185183289346 ],
  "disableMentions": true,
  "discordMessageFormat": "[$NAME] $MESSAGE",
  "chatMessageFormat": "**\u003c$NAME\u003e** $MESSAGE",
  "systemMessageFormat": "**$MESSAGE**"
}
```

To find someone's user ID, you need to enable "Developer Mode" on your Discord client:

![image](https://github.com/chunkaligned/fabric-discord-integration/assets/91440203/98bc627f-9096-4446-8d19-cc5d3a2f3d3b)

Then right-click the user and select "Copy User ID":

![image](https://github.com/chunkaligned/fabric-discord-integration/assets/91440203/c562d714-26b1-4930-a2b7-83c3ea34834d)

**Comment by Beavermon** [comment]
Thanks
