### ISSUE TITLE
Discord Names instead of Tags?

### ISSUE THREAD

**Issue by sparrowpaws** [chunkaligned/fabric-discord-integration#7]
Is it possible to just show the player name/nickname rather than the full Discord username with the tag at the end? I see it in the config as [$NAME] which shows [name#numbers] but is it possible to just have [name/nickname]? 

Great mod though! The only one for 1.19 I've gotten to work on my server, thank you!

**Comment by hkva** [comment]
Hi, thanks for trying it out. I can add another keyword called `$NICKNAME` that you can put in the config file, would that work?
